Organisation.create(name: 'Nova New Opportunities', website: 'www.novanewopps.org.uk')
Organisation.create(name: 'Midaye Somali Development Organisation', website: 'www.midaye.org.uk')
Programme.create(title: 'English')
Programme.create(title: 'Computers')
Programme.create(title: 'Sewing')
Client.create(first_name: 'Jane', last_name: 'Austen', email: 'jane@gmail.com', phone: '07961177777', address1: '150 Lancaster Road', address2: 'Flat 23', city: 'London', post_code: 'W10 4NU', country: 'UK')
Client.create(first_name: 'Anna', last_name: 'Jones', email: 'anna@gmail.com', phone: '07851177742', address1: '101 Lancaster Road', address2: 'Flat 24', city: 'London', post_code: 'W10 4NU', country: 'UK')
Client.create(first_name: 'Mary', last_name: 'Macintosh', email: 'mary@gmail.com', phone: '07761177736', address1: '172 Lancaster Road', address2: 'Flat 2', city: 'London', post_code: 'W10 4NU', country: 'UK')
Outcome.create(grade: '98', description: 'Increased self esteem')
